version: '3.1'

services:
  db:
    image: repo.rafi.cloud/docker-all/mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - C:/Daten/ITE/Repositories/spring6/spring-6-rest-mvc/src/scripts/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql